import AppLogo from "@/renderer/components/AppLogo";
import ExternalLinkButton from "@/renderer/components/buttons/ExternalLinkButton";
import Container from "@/renderer/components/Container";
import LoadingHarness from "@/renderer/components/LoadingHarness";
import NewReleaseAlert from "@/renderer/components/NewReleaseAlert";
import HorizontalStack from "@/renderer/components/stacks/HorizontalStack";
import VerticalStack from "@/renderer/components/stacks/VerticalStack";
import { useChangeLog } from "@/renderer/hooks/use-change-log";
import { useReleaseVersionChecker } from "@/renderer/hooks/use-release-version-checker";
import ReadmeParagraph from "@/renderer/views/home/componenets/ReadmeParagraph";
import ReadmeSection from "@/renderer/views/home/componenets/ReadmeSection";
import { CircularProgress, Typography } from "@mui/material";
import { Box } from "@mui/system";
import { useEffect, useMemo } from "react";
import { useRemark } from 'react-remark';

//TODO: may put in the ability to see previous version change logs
//TODO: change the styling of the elements generated by the markdown renderer

export default function HomeScreen() {


    const [changeLogMarkDown, setMarkdownSource] = useRemark();

    const {
        latestVersion,
        currentVersion,
        isNewVersion
    } = useReleaseVersionChecker();

    const changeLog = useChangeLog();

    useEffect(() => {
        if (!changeLog.data) return;
        const markdown = changeLog.data.find(x => x.version === currentVersion || x.version === `v${currentVersion}`)?.markdown ?? "";
        setMarkdownSource(markdown);
    }, [currentVersion, changeLog.data]);

    const currentChangeLog = useMemo(() => {
        if (!changeLog.data) return "";
        return changeLog.data.find(x => x.version === currentVersion || x.version === `v${currentVersion}`);
    }, [currentVersion, changeLog.data]);

    return <Container>

        <Box
            sx={{
                height: 75,
                textAlign: "center",
                mb: 2
            }}
        >
            <AppLogo />
        </Box>

        <VerticalStack gap={5}>

            {
                isNewVersion &&
                <NewReleaseAlert
                    latestVersion={latestVersion}
                />
            }

            <ReadmeSection
                title="📢 What's new in this version?"
            >

                <LoadingHarness
                    query={changeLog}
                    loadingState={<ChangeLogLoadingState />}

                >
                    {
                        currentChangeLog &&
                        <>
                            {changeLogMarkDown}
                        </>
                    }

                </LoadingHarness>
            </ReadmeSection>

            <ReadmeSection
                title="❤️ Support EmuSync"
            >
                <ReadmeParagraph>
                    EmuSync is free and always will be. However, if you like EmuSync and want to support it, you
                    can contribute via our <ExternalLinkButton href="https://www.patreon.com/EmuSync" text="Patreon" /> page.
                </ReadmeParagraph>

                <ReadmeParagraph>
                    Many thanks if you want to support EmuSync, but please only do so if want to and can afford to.
                </ReadmeParagraph>
            </ReadmeSection>

        </VerticalStack>
    </Container>
}



function ChangeLogLoadingState() {
    return <HorizontalStack>
        <Typography>
            Loading change log...
        </Typography>
        <CircularProgress size={16} />
    </HorizontalStack>
}